"use client";

import { useEffect, useState } from "react";
import { GlassCard } from "@/components/ui/glass-card";
import { Sparkles, Brain, Zap, ArrowRight, Globe, X, CheckCircle2, ChevronRight, Terminal } from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/store";
import { fetchUserAudits } from "@/store/slices/audit-slice";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { toast } from "sonner";

export default function AiInsightsPage() {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const currentReport = useAppSelector((state) => state.audit.currentReport);

  const [activeFix, setActiveFix] = useState<{ title: string; description: string; steps: string[] } | null>(null);

  useEffect(() => {
    dispatch(fetchUserAudits());
  }, [dispatch]);

  const domain = currentReport?.domain || "example.com";
  const recommendations = currentReport?.recommendations || [];

  const getStepsForFix = (title: string, desc: string): string[] => {
    const lower = title.toLowerCase();
    if (lower.includes("image") || lower.includes("compress")) {
      return [
        "Audit existing image dimensions to match desktop and mobile display containers.",
        "Convert image files to high-performance formats like WebP or AVIF using Squoosh or sharp.",
        "Implement responsive image source configuration using `srcset` and `sizes` attributes.",
        "Add loading='lazy' parameters to all images outside the initial viewport fold.",
      ];
    } else if (lower.includes("hsts") || lower.includes("strict-transport")) {
      return [
        "Access your web hosting provider configuration dashboard or web server configuration files (nginx.conf / .htaccess).",
        "Add the header: `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`.",
        "Verify SSL certification auto-renewal through Let's Encrypt or your custom domain SSL service.",
        "Restart the web service to load headers and verify utilizing SSL Labs analysis tool.",
      ];
    } else if (lower.includes("alt") || lower.includes("aria") || lower.includes("attribute")) {
      return [
        "Scan local HTML template source code and identify all `<img>` or visual SVG tags.",
        "If the image is decorative, add an empty `alt=''` attribute to omit from screen readers.",
        "If the asset is informative, write a clear, descriptive sentence outlining the image subject matter.",
        "Verify focusable buttons/inputs contain readable aria-label descriptions.",
      ];
    } else {
      return [
        `Locate the corresponding layout file or header configuration on your server.`,
        `Apply parameter edits matching the diagnostic instructions: "${desc}".`,
        `Confirm responsiveness behavior across local emulator viewports.`,
        `Commit configurations and run a fresh website audit scan to verify compliance.`,
      ];
    }
  };

  const user = useAppSelector((state) => state.auth.user);
  const isAdmin = user?.role === "admin";
  const userPlan = isAdmin
    ? "enterprise"
    : user?.plan || (typeof window !== "undefined" ? (localStorage.getItem("user_plan") as any) : null) || "starter";

  const handleExecuteFixClick = (rec: any) => {
    if (!isAdmin && userPlan === "starter") {
      toast.error("Professional Feature Locked", {
        description: "Step-by-step AI remediation instructions require a Pro or Enterprise plan. Upgrade to unlock!",
      });
      router.push("/upgrade");
      return;
    }

    const steps = getStepsForFix(rec.title, rec.description);
    setActiveFix({
      title: rec.title,
      description: rec.description,
      steps,
    });
  };

  return (
    <div className="flex flex-col gap-8 pb-16">
      {/* Header section */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-blue-600 mb-1">
            <Globe className="h-3.5 w-3.5" />
            <span>{domain}</span>
          </div>
          <h2 className="text-3xl font-black tracking-tight text-slate-900">
            Lumina AI Insights & Diagnostics
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Smart recommendations dynamically generated by scanning HTML structure, DOM, and network assets in MongoDB Atlas.
          </p>
        </div>

        <button
          onClick={() => router.push("/")}
          className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-full text-xs font-bold shadow-md hover:bg-blue-700 active:scale-95 transition-all cursor-pointer shrink-0"
        >
          <Sparkles className="h-4 w-4" />
          <span>Run New Scan</span>
        </button>
      </div>

      {/* Featured AI Recommendation Hero */}
      <GlassCard className="p-8 rounded-[28px] border-blue-200/80 bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white shadow-xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-3 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 border border-blue-400/30 text-blue-300 text-xs font-bold">
              <Brain className="h-4 w-4 text-blue-400 animate-pulse" />
              <span>Primary Lumina AI Insight for {domain}</span>
            </div>
            <h3 className="text-2xl font-black tracking-tight text-white">
              {recommendations[0]?.title || "Optimize Hero Asset Payload and Response Latency"}
            </h3>
            <p className="text-slate-300 text-sm leading-relaxed">
              {recommendations[0]?.description ||
                `We've identified potential performance gains across ${domain}. Implementing WebP image compression and deferring non-critical JavaScript will improve LCP scores.`}
            </p>
          </div>

          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10 border border-white/20 text-blue-300 shrink-0 shadow-lg backdrop-blur-md select-none">
            <Sparkles className="h-8 w-8 animate-pulse" />
          </div>
        </div>
      </GlassCard>

      {/* Diagnostic Recommendations Grid */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-800 tracking-tight">
          AI Action Items ({recommendations.length > 0 ? recommendations.length : 3})
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {(recommendations.length > 0
            ? recommendations
            : [
                {
                  id: "rec-1",
                  title: "Compress and Convert Images to WebP",
                  description: "Save up to 1.4MB payload per page load.",
                  severity: "critical" as const,
                  icon: "Zap",
                },
                {
                  id: "rec-2",
                  title: "Enforce HSTS Security Header",
                  description: "Prevent SSL downgrade attacks on domain traffic.",
                  severity: "high" as const,
                  icon: "Lock",
                },
                {
                  id: "rec-3",
                  title: "Add Missing Alt Attributes",
                  description: "Improve WCAG 2.1 AA screen reader accessibility.",
                  severity: "medium" as const,
                  icon: "Code",
                },
              ]
          ).map((rec) => (
            <GlassCard key={rec.id} className="p-6 rounded-[24px] border-slate-200/80 shadow-sm flex flex-col justify-between gap-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="p-2.5 rounded-xl bg-blue-50 text-blue-600 border border-blue-100/60 inline-block">
                    <Zap className="h-5 w-5" />
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-amber-50 text-amber-600 border border-amber-100">
                    {rec.severity}
                  </span>
                </div>
                <h4 className="text-base font-bold text-slate-900">{rec.title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed">{rec.description}</p>
              </div>

              <button
                onClick={() => handleExecuteFixClick(rec)}
                className="w-full py-2.5 bg-slate-50 hover:bg-blue-50 text-blue-600 border border-slate-200 hover:border-blue-200 rounded-xl text-xs font-bold active:scale-95 transition-all cursor-pointer"
              >
                Execute Fix
              </button>
            </GlassCard>
          ))}
        </div>
      </div>

      {/* Stepwise Fix Suggestions Popup Modal */}
      <AnimatePresence>
        {activeFix && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Overlay */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setActiveFix(null)}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
            />

            {/* Modal Content */}
            <motion.div
              initial={{ scale: 0.95, opacity: 0, y: 15 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 15 }}
              className="relative w-full max-w-2xl bg-white border border-slate-200 rounded-[28px] shadow-2xl p-6 md:p-8 z-10 overflow-hidden"
            >
              {/* Header */}
              <div className="flex justify-between items-start border-b border-slate-100 pb-4 mb-5">
                <div className="space-y-1 pr-8">
                  <div className="flex items-center gap-2 text-xs font-bold text-blue-600 uppercase tracking-widest">
                    <Terminal className="h-4 w-4" />
                    <span>Lumina AI Remediation Guide</span>
                  </div>
                  <h3 className="text-xl font-black text-slate-950 tracking-tight">
                    {activeFix.title}
                  </h3>
                </div>
                <button
                  onClick={() => setActiveFix(null)}
                  className="p-1.5 hover:bg-slate-50 rounded-xl text-slate-400 hover:text-slate-700 transition-colors cursor-pointer"
                  aria-label="Close modal"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>

              {/* Description */}
              <p className="text-slate-600 text-xs font-medium mb-6 leading-relaxed bg-slate-50 border border-slate-200/50 p-3.5 rounded-xl">
                {activeFix.description}
              </p>

              {/* Steps */}
              <div className="space-y-4 mb-6">
                <h4 className="text-xs font-black text-slate-400 uppercase tracking-wider">
                  Step-by-Step Instructions:
                </h4>
                <div className="flex flex-col gap-3.5">
                  {activeFix.steps.map((step, idx) => (
                    <div key={idx} className="flex gap-3 items-start">
                      <span className="flex h-6 w-6 items-center justify-center bg-blue-50 text-blue-600 border border-blue-100 rounded-lg text-xs font-bold shrink-0">
                        {idx + 1}
                      </span>
                      <p className="text-xs font-semibold text-slate-700 leading-relaxed pt-0.5">
                        {step}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Footer */}
              <div className="flex justify-end pt-2 border-t border-slate-100">
                <button
                  onClick={() => setActiveFix(null)}
                  className="px-6 py-2.5 bg-slate-950 hover:bg-slate-800 text-white rounded-full text-xs font-bold shadow-md hover:shadow-lg active:scale-95 transition-all cursor-pointer"
                >
                  Close Guide
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
