import { GlassCard } from "@/components/ui/glass-card";

export default function AiInsightsPage() {
  return (
    <div className="flex flex-col gap-6">
      <div>
        <h2 className="text-3xl font-black tracking-tight text-slate-900">
          AI Insights
        </h2>
        <p className="mt-1 text-sm text-muted-foreground">
          Intelligent diagnostic engine recommendations.
        </p>
      </div>

      <GlassCard className="flex min-h-[400px] flex-col items-center justify-center text-center">
        <div className="max-w-md">
          <h3 className="text-xl font-semibold tracking-tight text-foreground">
            Lumina AI Engine
          </h3>
          <p className="mt-2 text-sm text-muted-foreground">
            Smart recommendations dynamically generated by scanning files and network assets will be loaded here.
          </p>
        </div>
      </GlassCard>
    </div>
  );
}
