"use client";

import { useEffect } from "react";
import { GlassCard } from "@/components/ui/glass-card";
import { Sparkles, Brain, CheckCircle2, AlertTriangle, ArrowRight, Zap, Code, ShieldCheck, Search, Globe } from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/store";
import { fetchUserAudits } from "@/store/slices/audit-slice";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export default function AiInsightsPage() {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const currentReport = useAppSelector((state) => state.audit.currentReport);

  useEffect(() => {
    dispatch(fetchUserAudits());
  }, [dispatch]);

  const domain = currentReport?.domain || "example.com";
  const recommendations = currentReport?.recommendations || [];
  const issues = currentReport?.issues || [];

  const handleApplyFix = (title: string) => {
    toast.success("AI Automated Fix Applied", {
      description: `Executed automated optimization for ${title}.`,
    });
  };

  return (
    <div className="flex flex-col gap-8 pb-16">
      {/* Header section */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold text-blue-600 mb-1">
            <Globe className="h-3.5 w-3.5" />
            <span>{domain}</span>
          </div>
          <h2 className="text-3xl font-black tracking-tight text-slate-900">
            Lumina AI Insights & Diagnostics
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Smart recommendations dynamically generated by scanning HTML structure, DOM, and network assets in MongoDB Atlas.
          </p>
        </div>

        <button
          onClick={() => router.push("/")}
          className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-full text-xs font-bold shadow-md hover:bg-blue-700 active:scale-95 transition-all cursor-pointer shrink-0"
        >
          <Sparkles className="h-4 w-4" />
          <span>Run New Scan</span>
        </button>
      </div>

      {/* Featured AI Recommendation Hero */}
      <GlassCard className="p-8 rounded-[28px] border-blue-200/80 bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 text-white shadow-xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-3 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 border border-blue-400/30 text-blue-300 text-xs font-bold">
              <Brain className="h-4 w-4 text-blue-400 animate-pulse" />
              <span>Primary Lumina AI Insight for {domain}</span>
            </div>
            <h3 className="text-2xl font-black tracking-tight text-white">
              {recommendations[0]?.title || "Optimize Hero Asset Payload and Response Latency"}
            </h3>
            <p className="text-slate-300 text-sm leading-relaxed">
              {recommendations[0]?.description ||
                `We've identified potential performance gains across ${domain}. Implementing WebP image compression and deferring non-critical JavaScript will improve LCP scores.`}
            </p>
          </div>

          <button
            onClick={() => handleApplyFix(recommendations[0]?.title || "Primary Optimization")}
            className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl font-bold text-xs shadow-lg shadow-blue-600/30 active:scale-95 transition-all shrink-0 cursor-pointer"
          >
            <span>Apply AI Optimization</span>
            <ArrowRight className="h-4 w-4" />
          </button>
        </div>
      </GlassCard>

      {/* Diagnostic Recommendations Grid */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-800 tracking-tight">
          AI Action Items ({recommendations.length > 0 ? recommendations.length : 3})
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {(recommendations.length > 0
            ? recommendations
            : [
                {
                  id: "rec-1",
                  title: "Compress and Convert Images to WebP",
                  description: "Save up to 1.4MB payload per page load.",
                  severity: "critical" as const,
                  icon: "Zap",
                },
                {
                  id: "rec-2",
                  title: "Enforce HSTS Security Header",
                  description: "Prevent SSL downgrade attacks on domain traffic.",
                  severity: "high" as const,
                  icon: "Lock",
                },
                {
                  id: "rec-3",
                  title: "Add Missing Alt Attributes",
                  description: "Improve WCAG 2.1 AA screen reader accessibility.",
                  severity: "medium" as const,
                  icon: "Code",
                },
              ]
          ).map((rec) => (
            <GlassCard key={rec.id} className="p-6 rounded-[24px] border-slate-200/80 shadow-sm flex flex-col justify-between gap-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="p-2.5 rounded-xl bg-blue-50 text-blue-600 border border-blue-100/60 inline-block">
                    <Zap className="h-5 w-5" />
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-amber-50 text-amber-600 border border-amber-100">
                    {rec.severity}
                  </span>
                </div>
                <h4 className="text-base font-bold text-slate-900">{rec.title}</h4>
                <p className="text-xs text-slate-500 leading-relaxed">{rec.description}</p>
              </div>

              <button
                onClick={() => handleApplyFix(rec.title)}
                className="w-full py-2.5 bg-slate-50 hover:bg-blue-50 text-blue-600 border border-slate-200 hover:border-blue-200 rounded-xl text-xs font-bold active:scale-95 transition-all cursor-pointer"
              >
                Execute Fix
              </button>
            </GlassCard>
          ))}
        </div>
      </div>
    </div>
  );
}
